pim_catalog_family_index:
    path: /.{_format}
    defaults: { _controller: pim_catalog.controller.family:indexAction, _format: html }
    requirements:
        _format: html|json

pim_catalog_family_create:
    path: /create
    defaults: { _controller: pim_catalog.controller.family:createAction }

pim_catalog_family_edit:
    path: /{id}/edit
    defaults: { _controller: pim_catalog.controller.family:editAction }
    requirements:
        id: \d+

pim_catalog_family_remove:
    path: /{id}/remove
    defaults: { _controller: pim_catalog.controller.family:removeAction }
    requirements:
        id: \d+
    methods: [DELETE]

pim_catalog_family_addproductattributes:
    path: /{id}/attributes
    defaults: { _controller: pim_catalog.controller.family:addProductAttributesAction }
    requirements:
        id: \d+
    methods: [POST]

pim_catalog_family_removeproductattribute:
    path: /{familyId}/attribute/{attributeId}/remove
    defaults: { _controller: pim_catalog.controller.family:removeProductAttributeAction }
    requirements:
        familyId: \d+
        attributeId: \d+
    methods: [DELETE]

pim_catalog_family_history:
    path: /{id}/history.{_format}
    defaults: { _controller: pim_catalog.controller.family:historyAction, _format: html }
    requirements:
        id: \d+
        _format: html|json
