entities_config:
    Pim\Bundle\CatalogBundle\Model\Product:
        flexible_manager:             pim_catalog.manager.product
        flexible_class:               Pim\Bundle\CatalogBundle\Model\Product
        flexible_value_class:         Pim\Bundle\CatalogBundle\Model\ProductValue
        attribute_class:              Pim\Bundle\CatalogBundle\Model\ProductAttributeInterface
        attribute_option_class:       Pim\Bundle\CatalogBundle\Entity\AttributeOption
        attribute_option_value_class: Pim\Bundle\CatalogBundle\Entity\AttributeOptionValue
        default_locale:               null
        default_scope:                null
        flexible_init_mode:           required_attributes
